config/routes.rb
Rails.application.routes.draw do
  get 'reports/basic'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :todos
  get 'home/about'
  # root 'home#index'
  root 'todos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
         
         has_many :todo

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
    def google_oauth2
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
        else
            flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later'
            redirect_to new_user_registration_url  
        end   
    end
    
    def failure
        flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
        redirect_to new_user_registration_url
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def basic
    @a = 1
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    # @todo = Todo.new
    @todo = current_user.todo.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    # @todo = Todo.new(todo_params)
    @todo = current_user.todo.build(todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @todo = current_user.todo.find_by(id: params[:id])
    redirect_to todo_path, notice: "Not Authorized to edit this task" if @todo.nil?
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:sno, :task, :done, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Tracker', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'about', home_about_path, class: "nav-link" %>


      <% if user_signed_in? %>
     
        <li class="nav-item">
          <%= link_to 'add item', new_todo_path, class: "nav-link" %>           
        </li>
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reports', reports_basic_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
        </li>
          <% end %>
  </li>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>This is about page</h1>
<p>This is my about page.</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is not my first web page

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>InterTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %> 
    </br>
    <div class = "container">  
    <br/>
    <% if notice %>  
    <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/reports/basic.html.erb
<h1>Reports#basic</h1>
<p> <%= @a %> </p>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3" >
    <%= form.number_field :sno, class: "form-control", placeholder:"S.no" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :task, class:"form-control", placeholder:"Task" %>
  </div>

  <div class="field mb-3">
    <%= form.check_box :done , class:"form-check-input" %>
    <%= form.label :done , class:"form-check-label"%>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :todo_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  
  </br>


  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>

<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo, class:"btn btn-dark"%> |
<%= link_to 'Back', todos_path, class:"btn btn-dark" %>
<td><%= link_to 'Destroy', @todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-small" %></td>

app/views/todos/index.html.erb
<% if user_signed_in? %>

  <h1>Todos</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Sno</th>
        <th>Task</th>
        <th>Done</th>
        <th>Destroy</th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <% if todo.user_id == current_user.id %>        
        <tr>
          <td><%= todo.sno %></td>
          <td><%= link_to todo.task, todo %></td>
          <td><%= todo.done %></td>
          <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-small" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Todo', new_todo_path, class:"btn btn-primary"%>
<% else %>

<h1> Welome to ticker <h1>
<% end %>

app/views/todos/new.html.erb
<div class="card">
  <div class="card-header">
  <h1>Add Todo</h1>

  </div>
  <div class="card-body">
    <%= render 'form', todo: @todo %>
    </br>
  </div>
</div>
<%= link_to 'Back', todos_path%>

app/views/todos/show.html.erb
<div class=jumbotron> 

<h1>
<%= @todo.task %>
</h1>

<p class=container>

  <%= @todo.sno %> |

  <%= @todo.done %> 

</p>
</br>

<%= link_to 'Edit', edit_todo_path(@todo), class:"btn btn-secondary"%> |
<td><%= link_to 'Destroy', @todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-small" %></td>|

<%= link_to 'Back', todos_path, class:"btn btn-dark" %>
</div>  